#ifndef D_DEFAULT_SYS_RMCALL_PORT_HPP_
#define D_DEFAULT_SYS_RMCALL_PORT_HPP_
#include "cmodule_common.h"
#include "inc_stdlib.h"

#if defined(CMODULE_USE_RMCALL) && (CMODULE_USE_RMCALL > 0)

//#define CMODULE_RMCALL_UART LPUART2

// #define CMODULE_RMCALL_USE_HEARTBEAT (1U)
// #if defined(CMODULE_RMCALL_USE_HEARTBEAT) && (CMODULE_RMCALL_USE_HEARTBEAT > 0)
// #define CMODULE_RMCALL_PITISR_TIMELAG 100
// #define CMODULE_RMCALL_HEARTBEAT_TIMELAG 1000
// #define CMODULE_RMCALL_HEARTBEAT_FAIL_TH 2000
// #define CMODULE_RMCALL_HEARTBEAT_Callback() HardFault_IRQHandler()
// #endif // ! CMODULE_RMCALL_USE_HEARTBEAT

#define CMODULE_RMCALL_HEADER_MAGIC 0x68U
#define CMODULE_RMCALL_STATUS_MAGIC 0x86U

#endif // ! CMODULE_RMCALL_USE_HEARTBEAT

#endif // CMODULE_USE_RMCALL

#endif // ! D_DEFAULT_SYS_RMCALL_PORT_HPP_